### ISSUE TITLE
IOException at the end

### ISSUE THREAD

**Issue by sutambe** [psxpaul/gradle-execfork-plugin#22]
I see the following exception after a test finishes execution successfully. The exception has no impact on gradle build success. What is the exception about? I launch a native process listening on port 8080 in the `ExecFork` task.

```
Exception in thread "Thread-1124" java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:269)
        at com.github.psxpaul.stream.InputStreamPipe$thread$1.run(InputStreamPipe.kt:48)
        at java.lang.Thread.run(Thread.java:745)

BUILD SUCCESSFUL in 4s
9 actionable tasks: 4 executed, 5 up-to-date
```

**Comment by sutambe** [comment]
I think I know what this is. The remote process started by `ExecFork` crashes in my case. I think `ExecFork` is loosing connection and that's what we see here.

**Comment by KyleBS** [comment]
I've also been getting this error but came to a different conclusion. For me, it seems to be caused by logging things during shutdown such  as in the example at https://nodejs.org/api/process.html#process_signal_events. When I disabled the logging, the error went away.
